

import { User, Report, UserRole, ReportCategory } from './types';

export const MOCK_USERS: User[] = [
  { id: '1', username: 'admin', password: 'password', role: UserRole.ADMIN, name: 'مسؤول 4P' },
  { id: '2', username: 'bank', password: 'password', role: UserRole.BANK, name: 'مسئول البنك' },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'mock-001',
    atm_name: 'ماكينة البنك الأهلي - شارع الجلاء',
    atm_number: 'CAI-0112',
    serial_number: 'NBE-SN-88721',
    governorate: 'القاهرة',
    address: '4 شارع الجلاء، الأزبكية',
    maintenance_date: '2025-10-19T21:30:00.000Z',
    technical_report: 'تم تنظيف الواجهة الخارجية للماكينة وإصلاح الإضاءة. تم استبدال اللاصقات التالفة بأخرى جديدة والتخلص من المخلفات المحيطة.',
    notes: 'الماكينة تعمل بكفاءة بعد الصيانة.',
    before_photos: ['https://i.imgur.com/u74Y6oM.jpeg'],
    after_photos: ['https://i.imgur.com/gO18P8E.jpeg', 'https://i.imgur.com/Bf1b0D7.jpeg', 'https://i.imgur.com/i9hY66e.jpeg'],
    category: [ReportCategory.CORRECTIVE],
  },
  {
    id: 'mock-002',
    atm_name: 'ماكينة صراف آلي - ميدان رمسيس',
    atm_number: 'CAI-0255',
    serial_number: 'NBE-SN-91034',
    governorate: 'القاهرة',
    address: 'ميدان رمسيس، بجوار محطة القطار',
    maintenance_date: '2025-09-22T14:00:00.000Z',
    technical_report: 'تم تحديث الديكورات لتتوافق مع الهوية البصرية الجديدة للبنك. تم تركيب إضاءة LED جديدة وتغيير الواجهة الأمامية.',
    notes: 'تم الانتهاء من كافة الأعمال المطلوبة بنجاح.',
    before_photos: ['https://i.imgur.com/qLqZ08O.jpeg'],
    after_photos: ['https://i.imgur.com/r7wY2wA.jpeg', 'https://i.imgur.com/a9hY66e.jpeg'],
    category: [ReportCategory.MODERN],
  },
  {
    id: 'mock-003',
    atm_name: 'ماكينة البنك الأهلي - الدقي',
    atm_number: 'GIZ-0043',
    serial_number: 'NBE-SN-73319',
    governorate: 'الجيزة',
    address: 'شارع مصدق، الدقي',
    maintenance_date: '2025-09-15T11:45:00.000Z',
    technical_report: 'صيانة دورية للوحة المفاتيح والشاشة. تم تنظيف قارئ البطاقات.',
    notes: 'لا توجد ملاحظات.',
    before_photos: ['https://i.imgur.com/s7wY2wA.jpeg'],
    after_photos: ['https://i.imgur.com/r7wY2wA.jpeg'],
    category: [ReportCategory.CORRECTIVE],
  },
  {
    id: 'mock-004',
    atm_name: 'ATM - San Stefano',
    atm_number: 'ALX-0812',
    serial_number: 'NBE-SN-10283',
    governorate: 'الإسكندرية',
    address: 'مول سان ستيفانو، قسم الرمل',
    maintenance_date: '2025-10-02T16:00:00.000Z',
    technical_report: 'تركيب ديكور حديث للماكينة داخل المول.',
    notes: 'تم التنسيق مع إدارة المول.',
    before_photos: ['https://i.imgur.com/nLqZ08O.jpeg'],
    after_photos: ['https://i.imgur.com/Bf1b0D7.jpeg'],
    category: [ReportCategory.MODERN],
  },
  {
    id: 'mock-005',
    atm_name: 'ماكينة صراف - التجمع الخامس',
    atm_number: 'CAI-0931',
    serial_number: 'NBE-SN-11562',
    governorate: 'القاهرة',
    address: 'شارع التسعين، كايرو فيستيفال سيتي',
    maintenance_date: '2025-08-30T10:20:00.000Z',
    technical_report: 'إصلاح كسر في الجزء الجانبي من الديكور نتيجة اصطدام.',
    notes: 'تم استخدام مواد مقاومة للصدمات.',
    before_photos: [],
    after_photos: ['https://i.imgur.com/a9hY66e.jpeg'],
    category: [ReportCategory.CORRECTIVE],
  },
  {
    id: 'mock-006',
    atm_name: 'ماكينة البنك الأهلي - كورنيش المعادي',
    atm_number: 'CAI-0333',
    serial_number: 'NBE-SN-64481',
    governorate: 'القاهرة',
    address: 'كورنيش النيل، المعادي',
    maintenance_date: '2025-10-28T13:00:00.000Z',
    technical_report: 'صيانة شاملة للديكور وتغيير اللافتات الإرشادية.',
    notes: 'تمت الأعمال في وقت قياسي.',
    before_photos: ['https://i.imgur.com/qLqZ08O.jpeg'],
    after_photos: ['https://i.imgur.com/gO18P8E.jpeg'],
    category: [ReportCategory.CORRECTIVE, ReportCategory.MODERN],
  },
  {
    id: 'mock-007',
    atm_name: 'ATM - Hurghada Marina',
    atm_number: 'HRS-0010',
    serial_number: 'NBE-SN-20591',
    governorate: 'البحر الأحمر',
    address: 'مارينا الغردقة السياحي',
    maintenance_date: '2025-11-01T17:00:00.000Z',
    technical_report: 'تحديث الديكورات لمقاومة العوامل الجوية والرطوبة.',
    notes: 'تم استخدام مواد عازلة للرطوبة.',
    before_photos: [],
    after_photos: ['https://i.imgur.com/i9hY66e.jpeg'],
    category: [ReportCategory.MODERN],
  }
];